name: Trigger stolpersteine-muehlheim-site build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger_site_build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build in stolpersteine-muehlheim-site
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SITE_REPO_DISPATCH_TOKEN }}
          repository: schwitzkroko/stolpersteine-muehlheim-site
          event-type: stolpersteine_docs_updated
